# Generated by Django 2.1.1 on 2018-09-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0002_auto_20180902_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='title',
            new_name='que',
        ),
    ]
